name: gallery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  kiwi: ^5.0.1
  kiwi_generator: ^4.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
